function init(obj)
	xr_motivator.AddToMotivator(obj)
end

function actor_init(npc)
	npc:bind_object(actor_binder(npc))
end

local level_names = {
jupiter = 1,
k00_marsh = 1,
k01_darkscape = 1,
k02_trucks_cemetery = 1,  
l01_escape = 1,
l02_garbage = 1,
l03_agroprom = 1,
l04_darkvalley = 1,
l05_bar = 1,
l06_rostok = 1,
l07_military = 1,
l08_yantar = 1,
l09_deadcity = 1,
l10_limansk = 1,
l10_radar = 1,
l10_red_forest = 1,
l11_hospital = 1, 
l11_pripyat = 1,
l12_stancia = 1,
l13_generators = 1,
pripyat	= 1,
zaton = 1,
jupiter_underground = 1,
labx8 = 1,
l03u_agr_underground = 1,
l04u_labx18 = 1,
l08u_brainlab = 1,
l10u_bunker = 1,
l12u_control_monolith = 1,
l12u_sarcofag = 1,
l13u_warlab = 1,
fake_start = 1,
y04_pole = 1, 
sad = 1,
kurchatov_37 = 1, 
black_valley = 1,
predbannik = 1,
aver = 1, 
puzir = 1, 
la06_science_station = 0,
la22_forest = 0, 
la09_swamp = 0, 
kasiani = 1, 
la19_country = 0,  
la02_garbage = 0,  
la04_darkdolina = 0,
la14_rostok_factory = 0,
vokzal = 1, 
topi = 1,
la17_outskirts = 1,
labx5 = 1,
labx14 = 1,
promzona = 1,
deadlake = 1,
y05_anomles = 1,
labx27 = 1,
labx7 = 1,
poselok_ug = 1, 
way_in_zone = 1,  
prostranstvenniy_puzir = 1, 
digger_stash = 1,  
station_digger = 1,
la23_oldroad = 0,
okrest = 1,
grimwood = 1,
az_radar = 1,
bar_stalker = 1,
l15u_pripyat_und = 1,
lab_audron = 1,
collaider = 1,
labx2 = 0,
labx3 = 0,
labx6 = 0,
secret_forest = 1,
kanion = 1,
okrest_und_bar = 1,
okrest_und_bunker = 1,
okrest_und_fallstation = 1,
okrest_und_lab_24 = 1,
okrest_und_mtrs = 1,
office = 1,
niichaz = 1, 1,
church = 1,
collector22 = 1,
labx11 = 1,
}

----------------------------------------------------------------------------------------------------------------------
class "actor_binder" (object_binder)
----------------------------------------------------------------------------------------------------------------------
function actor_binder:__init (obj) super(obj)
	db.actor_binder = self
	--utils_data.debug_write("actor init start")
	self.bCheckStart = false
	--self.last_level_name = "nil" -- Not used for anything
	self.deimos_intensity = nil

	sound_theme.load_sound()

	self.last_detective_achievement_spawn_time 	= nil
	self.last_mutant_hunter_achievement_spawn_time	= nil

	bind_stalker_ext.actor_on_init(self)
	--utils_data.debug_write("actor init end")
end

----------------------------------------------------------------------------------------------------------------------
function actor_binder:net_spawn(se_abstract)
	--utils_data.debug_write("actor net spawn start")
	
	if object_binder.net_spawn(self,se_abstract) == false then
		return false
	end
	
	level.show_indicators()
	self.bCheckStart = true
	self.weapon_hide = false
	self.talking_state = false
	self.weapon_lowered_before_dialog = false
	
	db.add_actor(self.object)
	db.add_enemy(self.object)

	level_weathers.get_weather_manager():reset()
	
	db.actor.deimos_intensity = self.deimos_intensity
	self.deimos_intensity = nil
	if self.st.disable_input_time == nil then
		level.enable_input()
	end

	death_manager.init_drop_settings()
	self.spawn_frame = device().frame
	self.already_jumped = false
	self.loaded = false

	bind_stalker_ext.actor_on_net_spawn(self)
	
	if has_alife_info("spectrum_project_start") then 
       function_garbage.OnActorSpawned()
       --function_bar.OnActorSpawned()
       function_labx5.OnActorSpawned()
       function_labx14.OnActorSpawned()
	end	   

	sgm_callbacks.on_game_load()

	          --' Distemper 06.2008 --
	if rx_ai then rx_ai.actor_net_spawn() end

	--utils_data.debug_write("actor net spawn end")
	return true
end
----------------------------------------------------------------------------------------------------------------------
function actor_binder:net_destroy()
	--utils_data.debug_write("actor net destroy start")
	
	local sm = surge_manager.get_surge_manager()
	if (sm) then sm:finalize() end
	sm = psi_storm_manager.get_psi_storm_manager()
	if (sm) then sm:finalize() end 
	sm = level_weathers.get_weather_manager()
	if (sm) then sm:finalize() end
	
	xr_sound.stop_sounds_by_id(self.object:id())
	
	if (USE_MARSHAL) then 
		UnregisterScriptCallback("save_state",self)
	end

	bind_stalker_ext.actor_on_net_destroy(self)
	
	level.show_weapon(true)
	db.del_actor(self.object)
	db.delete_enemy(self.object)

	-- remove callbacks
	local t = {
				-- vanilla
				callback.inventory_info,
				callback.on_item_take,
				callback.on_item_drop,
				callback.task_state,
				callback.trade_sell_buy_item,
				callback.take_item_from_box,
				callback.use_object,
				
				-- coc
				callback.hud_animation_end,
				callback.hit,
				callback.key_press,
				callback.key_release,
				callback.key_hold,
				callback.actor_before_death,
				callback.on_attach_vehicle,
				callback.on_detach_vehicle,
				callback.on_use_vehicle,
				callback.weapon_fired,
				callback.weapon_jammed,
				callback.weapon_zoom_in,
				callback.weapon_zoom_out,
				callback.weapon_magazine_empty,
				callback.weapon_lowered,
				callback.weapon_raised,
				callback.weapon_no_ammo,
				callback.item_to_slot,
				callback.item_to_belt,
				callback.item_to_ruck,
				callback.on_foot_step,

				-- tc
				callback.map_location_added,
	}
	for i=1,#t do 
		if (t[i]) then 
			self.object:set_callback(t[i])
		end
	end

	if(_G.amb_vol~=0) then
		exec_console_cmd("snd_volume_eff "..tostring(_G.amb_vol))
		_G.amb_vol = 0
	end
	if(_G.mus_vol~=0) then
	    exec_console_cmd("snd_volume_music "..tostring(_G.mus_vol))
		_G.mus_vol = 0
	end
	if sr_psy_antenna.psy_antenna then
		sr_psy_antenna.psy_antenna:destroy()
		sr_psy_antenna.psy_antenna = false
	end
	
	object_binder.net_destroy(self)	
	--utils_data.debug_write("actor net destroy end")
end
----------------------------------------------------------------------------------------------------------------------
function actor_binder:reinit()
	object_binder.reinit(self)
	
	--utils_data.debug_write("actor reinit start")
	
	local npc_id = self.object:id()
	db.storage[npc_id] = empty_table(db.storage[npc_id])
	self.st = db.storage[npc_id]

	
	local t = {
				-- vanilla
				["inventory_info"] 			= bind_stalker_ext.actor_on_info_callback,
				["on_item_take"] 			= bind_stalker_ext.actor_on_item_take,
				["on_item_drop"] 			= bind_stalker_ext.actor_on_item_drop,
				["task_state"] 				= bind_stalker_ext.actor_on_task_callback,
				["trade_sell_buy_item"]		= bind_stalker_ext.actor_on_trade,
				["take_item_from_box"]		= bind_stalker_ext.actor_on_item_take_from_box,
				["use_object"]				= bind_stalker_ext.actor_on_item_use,
				
				-- coc
				["hud_animation_end"]		= bind_stalker_ext.actor_on_hud_animation_end,
				["hit"]						= bind_stalker_ext.actor_on_hit_callback,
				["key_press"]				= bind_stalker_ext.on_key_press,
				["key_release"]				= bind_stalker_ext.on_key_release,
				["key_hold"]				= bind_stalker_ext.on_key_hold,
				["actor_before_death"]		= bind_stalker_ext.actor_on_before_death,
				["on_attach_vehicle"]		= bind_stalker_ext.actor_on_attach_vehicle,
				["on_detach_vehicle"]		= bind_stalker_ext.actor_on_detach_vehicle,
				["on_use_vehicle"]			= bind_stalker_ext.actor_on_use_vehicle,
				["weapon_fired"]			= bind_stalker_ext.actor_on_weapon_fired,
				["weapon_jammed"]			= bind_stalker_ext.actor_on_weapon_jammed,
				["weapon_zoom_in"]			= bind_stalker_ext.actor_on_weapon_zoom_in,
				["weapon_zoom_out"]			= bind_stalker_ext.actor_on_weapon_zoom_out,
				["weapon_magazine_empty"]	= bind_stalker_ext.actor_on_weapon_magazine_empty,
				["weapon_lowered"]			= bind_stalker_ext.actor_on_weapon_lowered,
				["weapon_raised"]			= bind_stalker_ext.actor_on_weapon_raised,
				["weapon_no_ammo"]			= bind_stalker_ext.actor_on_weapon_reload, -- note: in engine this actually called on try_reload.
				
				["item_to_belt"]			= bind_stalker_ext.actor_item_to_belt,
				["item_to_slot"]			= bind_stalker_ext.actor_item_to_slot,
				["item_to_ruck"]			= bind_stalker_ext.actor_item_to_ruck,
				["on_foot_step"]			= bind_stalker_ext.actor_on_foot_step,

				-- tc
				["map_location_added"]		= markers_utils.actor_map_location_added,
	}
	for cb,func in pairs(t) do 
		if (callback[cb] and func) then 
			self.object:set_callback(callback[cb],func,self)
		end
	end
	
	if (USE_MARSHAL) then 
		RegisterScriptCallback("save_state",self)
	end
	
	bind_stalker_ext.actor_on_reinit(self)
	
	alife():set_objects_per_update(65534) -- To force all of alife to spawn and update at least once
	
	--utils_data.debug_write("actor reinit end")
end

----------------------------------------------------------------------------------------------------------------------

function actor_binder:update(delta)
	object_binder.update(self, delta)
	--utils_data.debug_write("actor update START")
	detector_fenix.up_main()
	
	if not (db.actor:alive()) then
		return
	end
	
	if self.bCheckStart then -- first update after netspawn
		self.bCheckStart = nil
		--utils_data.debug_write("actor first_update START")
		bind_stalker_ext.actor_on_first_update(self,delta)

		if not has_alife_info("global_dialogs") then
			self.object:give_info_portion("global_dialogs")
		end
		if not has_alife_info("level_changer_icons") then
			self.object:give_info_portion("level_changer_icons")
		end
		
		pda.fill_primary_objects()
		self.object:activate_slot(self.loaded_active_slot or 0)
		
		db.actor.afterFirstUpdate = true
		
		if (self.character_icon) then 
			db.actor:set_character_icon(self.character_icon)
		end
		
		local function set_obj_per_upd()
			alife():set_objects_per_update(20)
			return true
		end
		CreateTimeEvent(0,"obj_per_upd",1,set_obj_per_upd)
		
		printf("collectgarbage before=%sKb",collectgarbage("count")*1024)
		collectgarbage("collect")
		collectgarbage("collect")
		printf("collectgarbage after=%sKb",collectgarbage("count")*1024)
		--utils_data.debug_write("actor first_update END")
	end
	
	task_manager.get_task_manager():update()
	level_weathers.get_weather_manager():update()
	xr_sound.update(self.object:id())
	itms_manager.get_item_processor():update()

	-- ќбновление отключени€ ввода с клавиатуры.
	if (self.st.disable_input_time ~= nil and game.get_game_time():diffSec(self.st.disable_input_time) >= self.st.disable_input_idle) then
		level.enable_input()
		self.st.disable_input_time = nil
	end

	-- јпдейт пр€тание оружи€ игрока во врем€ диалога
	if self.object:is_talking() then
		if self.talking_state == false then
			local wpn = db.actor:active_item()
			if (wpn) then
				local can_be_lowered = wpn and IsWeapon(wpn) and ini_sys:r_bool_ex(wpn:section(), "can_be_lowered", false) or false
				local state = wpn:get_state()
				if (can_be_lowered and not(state == 0 or state == 1)) then can_be_lowered = false end
				
				if (can_be_lowered) then
					if (not game.actor_weapon_lowered()) then
						game.actor_lower_weapon(true)
						weapon_lowered_before_dialog = false
					else
						weapon_lowered_before_dialog = true
					end
				else
					self.object:hide_weapon()
					self.weapon_hide = true
				end
			end
			
			self.talking_state = true
		end
	else              
		if self.talking_state == true then
		
			if (self.weapon_hide) then
				self.weapon_hide = false
				self.object:restore_weapon()
			end
		
			if ((not weapon_lowered_before_dialog) and game.actor_weapon_lowered()) then
				game.actor_lower_weapon(false)
				weapon_lowered_before_dialog = false
			end
			
			self.talking_state = false
		end
	end

	-- обновление пси-антенны
	if sr_psy_antenna.psy_antenna then
		sr_psy_antenna.psy_antenna:update(delta)
	end

    trans_outfit.timer_trans() -- уменьшение дистанции видимости при одевании соотв. броников
	-- јпдейт доступности дл€ симул€ции.
	--simulation_objects.get_sim_obj_registry():update_avaliability(alife():actor())

	bind_stalker_ext.actor_on_update(self,delta)

	-- загрузка мода(посто€нное обновление)
      if mod_update() then
         sgm_queue.queue_main()
         sgm_variables.variables_main()
        if check_seconds(1) then
         sgm_inventory.inventory_main()
        end
        if check_seconds(1) then
         sgm_tasks.task_main()
        end
        if check_seconds(5) then
		 anthology_console.con_exec()
		 _s_timers.OnActorUpdate()
         sgm_world.world_main()
		 ins_tasks.task_main()
	     ins_tasks.OnActorUpdate()
		 	if has_alife_info("spectrum_project_start") then 
               function_escape.OnActorUpdate()
               function_garbage.OnActorUpdate()
               function_bar.OnActorUpdate()
               function_labx5.OnActorUpdate()
               function_labx14.OnActorUpdate()		 
            end		 
        end
      end

	if level_names[level.name()]==0 then
                anthology_console.level_la()
	end
	if level_names[level.name()]==1 then
                anthology_console.level_all()
	end

	if rx_ai then rx_ai.actor_update() end

	--utils_data.debug_write("actor update END 2")
end
----------------------------------------------------------------------------------------------------------------------
function actor_binder:save(packet)
	if rx_ai then rx_ai.actor_save() end
	set_save_marker(packet, "save", false, "actor_binder")
	object_binder.save(self, packet)
	set_save_marker(packet, "save", true, "actor_binder")
	
	if (USE_MARSHAL) then
		if (level_changing()) then
			save_var(db.actor,"heli_enemy_flag",nil)
			SendScriptCallback("on_level_changing")
		end
		return
	end
	--utils_data.debug_write("--------------- actor_binder:save -------- Start")
	set_save_marker(packet, "save", false, "actor_binder")

	if (level_changing()) then
		save_var(db.actor,"heli_enemy_flag",nil)
	end
	
	--alundaio
	utils_data.w_stpk(packet,"u8",level.get_game_difficulty(), "game difficulty")
	utils_data.w_stpk(packet,"CTime",self.st.disable_input_time, "disable input time")

	local deimos_exist = false
	for k,v in pairs(db.zone_by_name) do
		if(db.storage[v:id()] and db.storage[v:id()].active_scheme=="sr_deimos") then
			deimos_exist = true
			packet:w_bool(true)
			packet:w_float(db.storage[v:id()].sr_deimos.intensity)
		end
	end
	if not deimos_exist then
		packet:w_bool(false)
	end

	xr_logic.pstor_save_all(self.object, packet)
	
	sr_psy_antenna.save( packet )

	utils_data.w_stpk(packet,"bool",SIMBOARD.simulation_started, "sim started")

	xr_sound.actor_save(packet)
	--utils_data.w_stpk(packet,"stringZ",self.last_level_name,"last level name")
	game_statistics.save(packet)
	task_manager.get_task_manager():save(packet)
	packet:w_u8(self.object:active_slot())

	utils_data.w_stpk(packet,"CTime",self.last_detective_achievement_spawn_time, "detective spawn time")
	utils_data.w_stpk(packet,"CTime",self.last_mutant_hunter_achievement_spawn_time, "hunter spawn time")

	bind_stalker_ext.actor_on_save(self,packet)

	--utils_data.debug_write("--------------- actor_binder:save -------- End")
end

function actor_binder:load(reader)
	set_save_marker(reader, "load", false, "actor_binder")
	object_binder.load(self, reader)
	set_save_marker(reader, "load", true, "actor_binder")
	if (USE_MARSHAL) then
		self:load_state(alife_storage_manager.get_state()) -- fake because binder not ready when load_state callback is really made
		bind_stalker_ext.actor_on_load(self,reader)
		return
	end
	--utils_data.debug_write("actor_binder:load start")

	local game_difficulty_by_num = {
				[0] = "gd_novice",
				[1] = "gd_stalker",
				[2] = "gd_veteran",
				[3] = "gd_master"
				}
	local dif = game_difficulty_by_num[reader:r_u8()]
	if not (dif) then
		abort("actor_binder:load save corrupted!")
		return 
	end
	exec_console_cmd("g_game_difficulty "..dif)
	self.st.disable_input_time = utils_data.r_CTime(reader,"bind_stalker")

	xr_logic.pstor_load_all(self.object, reader)

	sr_psy_antenna.load(reader)
	SIMBOARD.simulation_started = reader:r_bool()

	xr_sound.actor_load(reader)
	--[[
	local n = reader:r_stringZ()
	if(n~="nil") then
		self.last_level_name = n
	end
	--]]
	game_statistics.load(reader)
	task_manager.get_task_manager():load(reader)

	self.loaded_active_slot = reader:r_u8()

	local stored_achievement_time = reader:r_bool()
	if stored_achievement_time == true then
		self.last_detective_achievement_spawn_time = utils_data.r_CTime(reader,"bind_stalker")
	end
	stored_achievement_time = reader:r_bool()
	if stored_achievement_time == true then
		self.last_mutant_hunter_achievement_spawn_time = utils_data.r_CTime(reader,"bind_stalker")
	end

	--utils_data.debug_write("actor_binder:load end")
end

----------------------------------------------------------------------------------------------------------------------
function actor_binder:save_state(m_data)
	--utils_data.debug_write(strformat("actor_binder:save_state BEFORE"))
	
	local state = alife_storage_manager.get_game_object_state(self.object,true)
	
	if not (state.actor_binder) then 
		state.actor_binder = {} 
	end 
	
	state.actor_binder.game_difficulty = level.get_game_difficulty()
	state.actor_binder.disable_input_time = self.st.disable_input_time
	state.actor_binder.simulation_started = SIMBOARD.simulation_started
	--state.actor_binder.last_level_name = self.last_level_name
	state.actor_binder.active_slot = self.object:active_slot()
	state.actor_binder.last_detective_achievement_spawn_time = self.last_detective_achievement_spawn_time
	state.actor_binder.last_mutant_hunter_achievement_spawn_time = self.last_mutant_hunter_achievement_spawn_time
	state.actor_binder.character_icon = self.character_icon
	
	if (sr_psy_antenna.psy_antenna and sr_psy_antenna.psy_antenna.global_state ~= 0 and not level_changing()) then 
		sr_psy_antenna.psy_antenna:save_state(m_data)
	end
	
	game_statistics.save_state(m_data)
	inventory_upgrades.save_state(m_data)
	xr_sound.actor_save_state(state)
	task_manager.save_state(m_data)
	level_weathers.get_weather_manager():save_state(m_data)
	surge_manager.save_state(m_data)
	psi_storm_manager.save_state(m_data)
	
	db.storage[0].pstor = db.storage[0].pstor or {}
	--utils_data.debug_write(strformat("actor_binder:save_state AFTER"))
end

function actor_binder:load_state(m_data)
	local state = alife_storage_manager.get_game_object_state(self.object)
	if not (state and state.actor_binder) then 
		return 
	end
	--utils_data.debug_write("actor_binder:load_state before")
	local game_difficulty_by_num = {
				[0] = "gd_novice",
				[1] = "gd_stalker",
				[2] = "gd_veteran",
				[3] = "gd_master"
				}
	exec_console_cmd("g_game_difficulty "..game_difficulty_by_num[state.actor_binder.game_difficulty or 3])
	self.st.disable_input_time = state.actor_binder.disable_input_time
	SIMBOARD.simulation_started = state.actor_binder.simulation_started
	--self.last_level_name = state.actor_binder.last_level_name
	self.loaded_active_slot = state.actor_binder.active_slot or 0
	self.last_detective_achievement_spawn_time = state.actor_binder.last_detective_achievement_spawn_time
	self.last_mutant_hunter_achievement_spawn_time = state.actor_binder.last_mutant_hunter_achievement_spawn_time
	self.character_icon = state.actor_binder.character_icon
	
	if (sr_psy_antenna.psy_antenna) then 
		sr_psy_antenna.psy_antenna:load_state(m_data)
	end
	
	game_statistics.load_state(m_data)
	inventory_upgrades.load_state(m_data)
	xr_sound.actor_load_state(state)
	task_manager.load_state(m_data)
	level_weathers.get_weather_manager():load_state(m_data)
	surge_manager.load_state(m_data)
	psi_storm_manager.load_state(m_data)
	
	if (state.pstor_all) then 
		db.storage[0].pstor = state.pstor_all
		state.pstor_all = nil
	end 

	if (state.pstor_ctime) then
		db.storage[0].pstor_ctime = state.pstor_ctime
		state.pstor_ctime = nil
	end
	
	state.actor_binder = nil
	--utils_data.debug_write("actor_binder:load_state after")
end 

function add_subtitles_on_hud(st_name, st_text, timer, timeout, info) -- !!!только дл€ катсцен!!!
    local hud = get_hud() 
	local isAdd = false

	if (cs_name) then hud:RemoveCustomStatic("text_sub_name") end
    if (cs_text) then hud:RemoveCustomStatic("text_sub_talk") end
	if (timeout == nil) then timeout = 0 end
	if (timer == nil) then timer = 50 end

	local timer_add = time_global() + (timeout * 100)
    local timer_del = time_global() + ((timer + timeout) * 100)
	
    level.add_call(
		function()
        	if (timer_add < time_global()) then
            	return true
        	end
        end,
        function()
			hud:HideActorMenu()
			hud:AddCustomStatic("text_sub_name", true)
			hud:AddCustomStatic("text_sub_talk", true)
			cs_name = hud:GetCustomStatic("text_sub_name")
			cs_name:wnd():TextControl():SetText(game.translate_string(st_name))
			cs_text = hud:GetCustomStatic("text_sub_talk")
			cs_text:wnd():TextControl():SetText(" "..game.translate_string(st_text))
			if (info ~= nil) then db.actor:give_info_portion(info) end
			isAdd = true
        end
    )
	level.add_call(
		function()
        	if (timer_del < time_global() and isAdd) then
            	return true
        	end 
        end,
        function()
			hud:RemoveCustomStatic("text_sub_name")
			hud:RemoveCustomStatic("text_sub_talk")
        end
    )
end

