--BY VODOXLEB
function on_xml_read()
    RegisterScriptCallback("on_xml_read", function(xml_file_name, xml_obj)
        -- XML file i want to change
        local xml_to_change = [[ui\ui_custom_msgs.xml]]
        -- Check if its the file i want to change
        if xml_file_name == xml_to_change then
			local my_new_option = [[<hud_frost1 x="0" y="0" width="1024" height="768" stretch="1">
		<texture>dinamic_hud\frost</texture>
	</hud_blood1>]]
            xml_obj:insertFromXMLString(my_new_option)
        end
    end)
end