--[[
	
	EverybodyLies
	03 February 2022

	RELEASE:
	- Fixed bug in UICellItem:Add_Icon/Add_Shadow functions when icon inside rotated cells is displayed incorrectly.
	UPD.03/02/2022:
	- Added UICellItem:Create_Layer() fix from RavenAscendant icon override script.
	- Fixed compatibility issue then player have an icon override script.
	- Script renamed to 'utils_ui_icon_rotation_fix_mcm.script' for loading early enough to modify the New Game screens.
	UPD.11/02/2022:
	- Upgrade icon in rotated cell is now displayed on the top-right corner.
	UPD.13/02/2022:
	- Added shadows for scopes, silencers and grenade launchers! Compatible with icon_override.
	TODO:
	+ Add shadows for equipped atachments on weapon.
	- Add support for custom attachment icon on weapon, not only attachment item icon itself.

]]--

local sync_element          = utils_xml.sync_element
local ratio = utils_xml.screen_ratio()

function utils_ui.UICellItem:InitControls(path, st)
	local xml = self:GetXML()
	
	-- Free cell
	local free_cell = (type(st) == "table")
	if free_cell then
		st = self.container.xml:InitStatic(st.path, st.base)
		self.st = st
	end

	self.hl = xml:InitStatic(path .. ":" .. self.cx .. ":highlight", st)
	self.cell = xml:InitStatic(path .. ":" .. self.cx, st)
	self.shadow = xml:InitStatic(path .. ":" .. self.cx .. ":pic", self.cell)
	self.shadow_ico_scope = xml:InitStatic(self.path .. ":" .. self.cx .. ":pic", self.shadow)
	
	self.base_icon = xml:InitStatic(path .. ":" .. self.cx .. ":pic", self.cell)
	self.ico = xml:InitStatic(path .. ":" .. self.cx .. ":pic", self.cell)

	-- Highlight texture
	--self.hl:InitTexture("ui_button_inv_h")
	self.hl:SetStretchTexture(true)
	self.hl:Show(false)
	sync_element(self.hl, self.cell)
end

function has_dovetail_scope(obj)
	if not obj then
		return false
	end

	local sec = obj:section()
	local scope = (not utils_item.has_scope(sec)) and utils_item.get_attached_scope(obj)
	if scope then
		local scope_fam = ini_sys:r_string_ex(sec,"modular_scope_group")
		if scope_fam == "scope_group_dovetail" then 
			return true
		end
	end

	return false
end


function utils_ui.UICellItem:Set(obj, area)
	local xml = self:GetXML()
	local path = self.path
	local is_obj = (self.showcase == 0)
	local grid_size = self.grid_size
	
	local sec = is_obj and obj:section() or obj
	local clsid = is_obj and obj:clsid()

	local x = SYS_GetParam(2,sec, "inv_grid_x")
	local y = SYS_GetParam(2,sec, "inv_grid_y")
	local w = SYS_GetParam(2,sec, "inv_grid_width")
	local h = SYS_GetParam(2,sec, "inv_grid_height")
	local extra_h = h
	local rot = self.ico:GetHeading() > 0
	local has_dovetail = not rot and is_obj and has_dovetail_scope(obj)
	-- expand only cell with height 1
	if has_dovetail and extra_h == 1 then
	    extra_h = extra_h + 1
	end
	
	if not x or not y or not w or not h then
		return false
	end
	
	x = x * grid_size
	y = y * grid_size
	w = w * grid_size
	h = h * grid_size
	extra_h = extra_h * grid_size
	
	self.ID = is_obj and obj:id() or nil
	self.section = sec
	self.area = area
	--self.X = x
	--self.Y = y
	self.W = w
	self.H = h

	-- Trade mode
	--if self:Check_TradeMode(obj, sec) then
		--return false
	--end
	
	-- Cell pos
	if area and (not self.manual) then
		local area_x = ((area.x * grid_size) - grid_size) * ratio
		local area_y = (area.y * grid_size) - grid_size
		local area_xl = self.grid_line * area.x
		local area_yl = self.grid_line * area.y

		self.cell:SetWndPos(vector2():set( area_x + area_xl , area_y + area_yl ))
		self.cell:SetWndSize(vector2():set(w * ratio , extra_h))
		sync_element(self.hl, self.cell)
		self:Print(nil, "Set for [%s]  in (%s,%s,%s,%s)", sec, area_x, area_y, w, h)
		
	-- Cell pos (free cell)
	elseif self.st then 
		local st_x = ((self.st:GetWidth() /2) - ((w * ratio) /2))
		local st_y = ((self.st:GetHeight() /2) - (h /2))
		self.cell:SetWndPos(vector2():set( st_x , st_y ))
		self.cell:SetWndSize(vector2():set(w * ratio , extra_h))
		sync_element(self.hl, self.cell)
		self:Print(nil, "Set for [%s]  in free cell", sec)
	end
	
	-- Icon
	self:Add_Icon(sec, w, h)
	self:Add_Shadow(sec, w, h)
	
	-- Icon layers
	self:Add_Layers(xml, obj, sec, clsid)
	
	-- Update cell
	local is_updated = self:Update(is_obj and obj)
	if (not is_updated) then
		self:Print(nil, "Updating failed for [%s] | Reset cell", sec)
		self:Reset()
		return false
	end

	self.cell:Show(true)
	return true
end

function utils_ui.UICellItem:Reset()
	self.ID = nil
	self.section = nil
	if self.childs then
		empty_table(self.childs)
	end
	
	empty_table(self.flags)
	
	self:Highlight(false)
	if (self.manual) then
		self.base_icon:Show(false)
		self.ico:Show(false)
		self.shadow:Show(false)
		if self.bar then self.bar:Show(false) end
		if self.cnt then self.cnt:Show(false) end
		if self.upgr then self.upgr:Show(false) end
		if self.ctxt then self.ctxt:Show(false) end
		if self.ctxts then self.ctxts:Show(false) end
	else
		if (self.showcase ~= 2) and self.container["FreeRoom"] then
			-- Freeing cell area
			local a = self.area
			if a then
				self.container:FreeRoom(a.y, a.x, a.w, a.h)
			else
				self:Show(false)
			end
		end
		
		self:Show(false)
	end
end

--  Credits to RavenAscendant for this fix
function utils_ui.UICellItem:Create_Layer(ele, base, sec_m, sec_l, str_x, str_y, str_scale)
	local ratio = utils_xml.screen_ratio()
	local grid_size = self.grid_size
	local x = str_x and SYS_GetParam(2,sec_m, str_x) or 0 
	local y = str_y and SYS_GetParam(2,sec_m, str_y) or 0
	if sec_m and ini_sys:r_bool_ex(sec_m, "modular_attachments", false) then
        local inv_offset_x = SYS_GetParam(2, sec_l, "inv_offset_x")
        local inv_offset_y = SYS_GetParam(2, sec_l, "inv_offset_y")
        if inv_offset_x then
            x = x - inv_offset_x
        end
        if inv_offset_y then
            y = y - inv_offset_y
        end
    end
	local w = SYS_GetParam(2,sec_l, "inv_grid_width",1) * grid_size
	local h = SYS_GetParam(2,sec_l, "inv_grid_height",1) * grid_size
	local scale = str_scale and SYS_GetParam(2,sec_m, str_scale) or 1
	local scale_pos = scale * (grid_size/50)

	local rot = ele:GetHeading() > 0
	local x_s = x * ratio * scale_pos
	local y_s = y * scale_pos * 1.02
	local w_s = w * ratio * scale
	local h_s = h * scale
	local w_off = (w_s/2)
	local h_off = (h_s/2)

	if rot then
		-- despite rotation, the dimensions of the base icon do not change! 
		-- Move start pos to match the one for rotated base icon
		-- Base icon rotates on its center. To calculate where the upper left corner went move to the center of the window then move along the rotated image
		local w_b, h_b = base:GetWidth(), base:GetHeight()
		local x_st = (w_b/2) - (h_b/2)*ratio --When the engine rotates an image it doesn't get streched. Which means it is efectivly ratio corected and centered, to move out from the center of the window to the top of the gun, we need to ratio corect the old height to get to the new width.
		local y_st = (h_b/2) + (w_b/2) --no ratio corection here because movement out from the center is along the veritcal axis where no ratio adjustment is needed
		-- printf("w:%s,h:%s, y:%s,x:%s",w_b, h_b, y_st,x_st)
		-- On 90 rotation, x and y are inverted, y axis goes negative simulate normal x movement
		x_s = x_st * 1.02 + (y * ratio * scale_pos)
		y_s = y_st - (x * scale_pos) 
		w_s = w * scale --window size doesn't change despite rotation so these dimensions don't get swapped. Because the icon is getting rotated ratio corection is moot and would just need to be compensated for in h_off
		h_s = h * scale
		w_off = (h_s/2) * ratio --because this is moving along the x axis it needs ratio corection
		h_off = -(w_s/2)
	end
	
	ele:InitTexture( utils_xml.get_icons_texture(sec_l) )
	ele:SetTextureRect(Frect():set( utils_xml.get_item_axis(sec_l, nil, true) ))
	ele:SetStretchTexture(true)
	ele:SetWndPos(vector2():set( x_s + w_off , y_s + h_off ))
	ele:SetWndSize(vector2():set( w_s , h_s ))
	ele:Show(true)
end

-------------------------------------------------------------------

function utils_ui.UICellItem:Add_Attachements(xml, obj, sec, clsid)
	-- Hide attachments
	if self.ico_scope then self.ico_scope:Show(false) end
	if self.shadow_ico_scope then self.shadow_ico_scope:Show(false) end
	if self.ico_sil then
		self.ico_sil:Show(false)
		self.shadow_sil:Show(false)
	end
	if self.ico_gl then
		self.ico_gl:Show(false)
		self.shadow_gl:Show(false)
	end
	
	-- On full stacking, hide counter
	if self.container.stack_all and (self.childs and is_not_empty(self.childs)) then
		return
	end
	
	-- No attachments on showcase cells
	if (self.showcase ~= 0) then
		return
	end
	
	-- No attachments for non-firearms
	local magazined_wpn = IsWeapon(nil,clsid) and (not IsItem("fake_ammo_wpn",sec))
	if (not magazined_wpn) then
		return
	end

	-- Scope
	local scope = (not utils_item.has_scope(sec)) and utils_item.get_attached_scope(obj)
	if scope then
		if (not xml) then 
			xml = self:GetXML()
		end
		local scope_fam = ini_sys:r_string_ex(sec,"modular_scope_group")
		if scope_fam ~= "scope_group_dovetail" then 
			self.ico_scope = xml:InitStatic(self.path .. ":" .. self.cx .. ":pic", self.ico)
		else
			self.ico_scope = xml:InitStatic(self.path .. ":" .. self.cx .. ":pic", self.base_icon)
		end
		local modular_attachments = ini_sys:r_bool_ex(sec, "modular_attachments", false)
		if modular_attachments then
			local scopes = ini_sys:r_bool_ex(sec, "modular_attachments", false)
            self:Create_Layer(self.ico_scope, self.base_icon, sec, scope, "inv_scope_x", "inv_scope_y")
            self:Print(nil, "Show scope")
            self:Create_Layer(self.shadow_ico_scope, self.shadow, sec, scope, "inv_scope_x", "inv_scope_y")
        else
            local scopes_sect = utils_item.get_param(sec, obj:id(), "scopes_sect", "string", false)
            self:Create_Layer(self.ico_scope, self.base_icon, scopes_sect, scope, "scope_x", "scope_y")
            self:Print(nil, "Show scope")
            self:Create_Layer(self.shadow_ico_scope, self.shadow, scopes_sect, scope, "scope_x", "scope_y")
        end
		
		self.shadow_ico_scope:SetTextureColor( GetARGB(200, 20, 20, 20) )
		self:Print(nil, "Show scope shadow")
	end

	-- Silencer
	local sil = utils_item.get_attached_silencer(obj)
	if sil then
		if (not self.ico_sil) then
			if (not xml) then 
				xml = self:GetXML()
			end
			self.ico_sil = xml:InitStatic(self.path .. ":" .. self.cx .. ":pic", self.ico)
			self.shadow_sil = xml:InitStatic(self.path .. ":" .. self.cx .. ":pic", self.shadow)
		end
		self:Create_Layer(self.ico_sil, self.ico, sec, sil, "silencer_x", "silencer_y")
		self:Print(nil, "Show silencer")

		self:Create_Layer(self.shadow_sil, self.shadow, sec, sil, "silencer_x", "silencer_y")
		self.shadow_sil:SetTextureColor( GetARGB(200, 20, 20, 20) )
		self:Print(nil, "Show silencer shadow")
	end
	
	-- Grenade Launcher
	local gl = utils_item.get_attached_gl(obj)
	if gl then
		if (not self.ico_gl) then
			if (not xml) then 
				xml = self:GetXML()
			end
			self.ico_gl = xml:InitStatic(self.path .. ":" .. self.cx .. ":pic", self.ico)
			self.shadow_gl = xml:InitStatic(self.path .. ":" .. self.cx .. ":pic", self.shadow)
		end
		self:Create_Layer(self.ico_gl, self.ico, sec, gl, "grenade_launcher_x", "grenade_launcher_y")
		self:Print(nil, "Show grenade launcher")

		self:Create_Layer(self.shadow_gl, self.shadow, sec, gl, "grenade_launcher_x", "grenade_launcher_y")
		self.shadow_gl:SetTextureColor( GetARGB(200, 20, 20, 20) )
		self:Print(nil, "Show grenade launcher shadow")
	end
end

function utils_ui.UICellItem:Add_Icon(sec, w, h)
	local rot = self.ico:GetHeading() > 0

	self.base_icon:SetWndSize(vector2():set( w * (rot and 1 or utils_xml.screen_ratio()) , h ))
	utils_xml.align_to_center(self.base_icon, self.cell)
	self.base_icon:Show(true)
	
	self.ico:InitTexture( utils_xml.get_icons_texture(sec) )
	self.ico:SetTextureRect(Frect():set( utils_xml.get_item_axis(sec, nil, true) ))
	self.ico:SetStretchTexture(true)
	self.ico:SetWndSize(vector2():set( w * (rot and 1 or utils_xml.screen_ratio()) , h ))
	self.ico:Show(true)
	utils_xml.align_to_center(self.ico, self.cell)
	
	self:Print(nil, "Show icon")
end


function utils_ui.UICellItem:Add_Shadow(sec, w, h)
	local rot = self.shadow:GetHeading() > 0

	local shadow_offset_x, shadow_offset_y = 1, 2

	self.shadow:InitTexture( utils_xml.get_icons_texture(sec) )
	self.shadow:SetTextureRect(Frect():set( utils_xml.get_item_axis(sec, nil, true) ))
	self.shadow:SetStretchTexture(true)
	self.shadow:SetWndSize(vector2():set( w * (rot and 1 or utils_xml.screen_ratio()) , h ))
	self.shadow:Show(true)
	utils_xml.align_to_center(self.shadow, self.cell)
	
	local pos = self.ico:GetWndPos()
	self.shadow:SetWndPos( vector2():set( pos.x + shadow_offset_x , pos.y + shadow_offset_y ) )
	self.shadow:SetTextureColor( GetARGB(200, 20, 20, 20) )
	
	self:Print(nil, "Show shadow")
end


function utils_ui.UICellItem:Add_Upgrade(xml, obj, sec)
	-- Hide upgrade indicator
	if self.upgr then
		self.upgr:Show(false)
	end
	
	-- On full stacking, hide upgrade indicator
	if self.container.stack_all and (self.childs and is_not_empty(self.childs)) then
		return
	end
	
	-- Bar is applied only to upgraded items
	if (not utils_item.has_upgrades(obj, sec)) then
		return
	end
	
	-- Init if it doesn't exist
	if (not self.upgr) then
		if (not xml) then 
			xml = self:GetXML()
		end
		self.upgr = xml:InitStatic(self.path .. ":cell:upgrade", self.ico)
	end
	
	-- Positioning
	local ico = self.ico
	local xx = 1 * 1024/device().width --[px]
	local yy = 1 * 768/device().height --[px]

	local rot = ico:GetHeading() > 0

	if rot then
	-- top-right corner
		local x_offset = -4 * 1024/device().width + (self.cell:GetWidth() - self.upgr:GetWidth()) --[px]
		local y_offset = 4 * 768/device().height --[px]
	-- bottom-left corner
	--	x_offset = 4  * 1024/device().width --[px]
	--	y_offset = -4  * 768/device().height + (cell_h - self.upgr:GetHeight()) --[px]

		xx = x_offset - (self.cell:GetWidth() - ico:GetWidth())/2
		yy = y_offset - (self.cell:GetHeight() - ico:GetHeight())/2
	end
	
	self.upgr:SetWndPos(vector2():set( xx , yy ))
	self.upgr:Show(true)
	
	self:Print(nil, "Show upgrade indicator")
end
