craft_recipes = {
	jar = {
		af_mask_filter_homemade = {
			"jar, charcoal:1, prt_o_fabrics_1",
			"jar, charcoal:1, prt_o_fabrics_3",
			"jar, charcoal:1, prt_o_fabrics_2",
			"jar, charcoal:1, prt_o_fabrics_4",
		},
	},
	
	drug_charcoal = {
		af_mask_filter_homemade = {
			"drug_charcoal:5, prt_o_fabrics_1",
			"drug_charcoal:5, prt_o_fabrics_3",
			"drug_charcoal:5, prt_o_fabrics_2",
			"drug_charcoal:5, prt_o_fabrics_4",
		},
	},
}

demonized_crafter.add_craft_recipe(craft_recipes)
