-- Consolidate Tanks and Filters for Toxic Air - ilrathCXV (last edit: 04/13/2024)
-- Adapted from GAMMA's Artefact Melter Charge script

local gc = game.translate_string

local filters = {
["af_mask_filter_homemade"] = 6.7,
["af_mask_filter_ms4"] = 4,
["af_mask_filter_1"] = 3.3,
["af_mask_filter_1sci"] = 2.9,
["af_mask_filter_dp1"] = 5,
["af_mask_filter_2"] = 2.2,
["af_mask_filter_2dolg"] = 2,
["af_mask_filter_mof6"] = 2.5,
["af_mask_filter_3"] = 1.7,
["af_mask_filter_fp5"] = 0,	-- debug item so it is set to zero to ignore
["af_mask_filter_r18"] = 1.8,
["af_mask_filter_3isg"] = 1.5,
}

local tanks = {
["af_oxygen_tank_1"] = 8,
["af_oxygen_tank_1soviet"] = 8,
["af_oxygen_tank_2"] = 4,
["af_oxygen_tank_3"] = 2,
["tank_filling_station"] = 1,
}

local function on_item_drag_dropped(obj_1, obj_2, slot_from, slot_to)
	-- Check if both items are in the the player's bag
	if not (slot_from == EDDListType.iActorBag and slot_to == EDDListType.iActorBag) then
        return
    end
		
	local sec_1 = obj_1:section()
	local sec_2 = obj_2:section()
	
	local is_tank_1 = tanks[sec_1] or false
	local is_tank_2 = tanks[sec_2] or false
	
	local is_filter_1 = filters[sec_1] or false
	local is_filter_2 = filters[sec_2] or false
	
	local original_val = obj_2:condition()
	local regen_val = obj_1:condition()
	
	-- first item is neither a tank nor a filter
	if (not is_tank_1) and (not is_filter_1) then return end
	
	if (original_val > 0.99) or (regen_val < 0.01) then return end
	
	if (sec_1 == "tank_filling_station") and is_tank_2 then
		local regen_koef = is_tank_2
		local new_val = original_val + regen_val * regen_koef
		
		if new_val > 1 then
			obj_2:set_condition(clamp(new_val, original_val, 1))
			obj_1:set_condition(clamp(((new_val - 1)/regen_koef), 0.01, regen_val))
			local tanks_filled_snd = sound_object("toxic_air\\ta_tank_on")
			tanks_filled_snd:play_no_feedback(db.actor, sound_object.s2d, 0, VEC_ZERO, 1.0, 1.0)
		else
			obj_1:set_condition(0)
			obj_2:set_condition(clamp(new_val, original_val, 1))
			local tanks_consolidated_snd = sound_object("toxic_air\\ta_tank_off")
			tanks_consolidated_snd:play_no_feedback(db.actor, sound_object.s2d, 0, VEC_ZERO, 1.0, 1.0)
		end
		return
	elseif is_tank_1 and (sec_2 == "tank_filling_station") then
		local regen_koef = is_tank_1
		local new_val = original_val + regen_val / regen_koef
		
		if new_val > 1 then
			obj_2:set_condition(clamp(new_val, original_val, 1))
			obj_1:set_condition(clamp(((new_val - 1) * regen_koef), 0.01, regen_val))
			local tanks_filled_snd = sound_object("toxic_air\\ta_tank_on")
			tanks_filled_snd:play_no_feedback(db.actor, sound_object.s2d, 0, VEC_ZERO, 1.0, 1.0)
		else
			alife_release(obj_1)
			obj_2:set_condition(clamp(new_val, original_val, 1))
			local tanks_consolidated_snd = sound_object("toxic_air\\ta_tank_off")
			tanks_consolidated_snd:play_no_feedback(db.actor, sound_object.s2d, 0, VEC_ZERO, 1.0, 1.0)
		end
		return
	end
	
	if is_filter_1 and (sec_2 == "tank_filling_station") then
		local regen_koef = is_filter_1
		local new_val = original_val + regen_val / regen_koef
		
		if new_val > 1 then
			obj_2:set_condition(clamp(new_val, original_val, 1))
			obj_1:set_condition(clamp(((new_val - 1) * regen_koef), 0.01, regen_val))
			local tanks_filled_snd = sound_object("toxic_air\\ta_tank_on")
			tanks_filled_snd:play_no_feedback(db.actor, sound_object.s2d, 0, VEC_ZERO, 1.0, 1.0)
		else
			alife_release(obj_1)
			obj_2:set_condition(clamp(new_val, original_val, 1))
			local tanks_consolidated_snd = sound_object("toxic_air\\ta_tank_off")
			tanks_consolidated_snd:play_no_feedback(db.actor, sound_object.s2d, 0, VEC_ZERO, 1.0, 1.0)
		end
		return
	end
	
	if is_tank_1 and is_tank_2 and (is_tank_1 == is_tank_2) then
		local new_val = original_val + regen_val
		
		if new_val > 1 then
			obj_2:set_condition(clamp(new_val, original_val, 1))
			obj_1:set_condition(clamp((new_val - 1), 0.01, regen_val))
			local tanks_filled_snd = sound_object("toxic_air\\ta_tank_on")
			tanks_filled_snd:play_no_feedback(db.actor, sound_object.s2d, 0, VEC_ZERO, 1.0, 1.0)
		else
			alife_release(obj_1)
			obj_2:set_condition(clamp(new_val, original_val, 1))
			local tanks_consolidated_snd = sound_object("toxic_air\\ta_tank_off")
			tanks_consolidated_snd:play_no_feedback(db.actor, sound_object.s2d, 0, VEC_ZERO, 1.0, 1.0)
		end
		return
	elseif is_tank_1 and is_tank_2 and (is_tank_1 ~= is_tank_2) then
		news_manager.send_tip(db.actor, gc("st_not_same_tank"), 0, nil, 5000)
	end
	
	if is_filter_1 and is_filter_2 and (is_filter_1 == is_filter_2) then
		local new_val = original_val + regen_val
		
		if new_val > 1 then
			obj_2:set_condition(clamp(new_val, original_val, 1))
			obj_1:set_condition(clamp((new_val - 1), 0.01, regen_val))
		else
			alife_release(obj_1)
			obj_2:set_condition(clamp(new_val, original_val, 1))
		end
		
		local filter_snd = sound_object("toxic_air\\filter_use_on")
		filter_snd:play_no_feedback(db.actor, sound_object.s2d, 0, VEC_ZERO, 1.0, 1.0)
		xr_sound.set_sound_play(AC_ID,"filter_use_on")
		
		return
	elseif is_filter_1 and is_filter_2 and (is_filter_1 ~= is_filter_2) then
		news_manager.send_tip(db.actor, gc("st_not_same_filter"), 0, nil, 5000)
	end
	
end

function menu_refilling_tank(obj)
	local sec = obj and obj:section()
	if not (sec == "tank_filling_station") then return end
	return gc("st_refilling_tank_on_belt")
end


function refilling_tank_on_belt(obj)
	local regen_val = obj:condition()
	db.actor:iterate_belt( function(owner, tank)
		local t_sec = tank:section()
		
		if tanks[t_sec] then
			local t_cond = tank:condition()
			
			if (t_cond > 0.99) or (regen_val < 0.01) then return end
			
			local regen_koef = tanks[t_sec] or 1
			local new_val = t_cond + regen_val * regen_koef
			
			if new_val > 1 then
				tank:set_condition(clamp(new_val, t_cond, 1))
				obj:set_condition(clamp(((new_val - 1)/regen_koef), 0.01, regen_val))
				local tanks_filled_snd = sound_object("toxic_air\\ta_tank_on")
				tanks_filled_snd:play_no_feedback(db.actor, sound_object.s2d, 0, VEC_ZERO, 1.0, 1.0)
			else
				obj:set_condition(0)
				tank:set_condition(clamp(new_val, t_cond, 1))
				local tanks_consolidated_snd = sound_object("toxic_air\\ta_tank_off")
				tanks_consolidated_snd:play_no_feedback(db.actor, sound_object.s2d, 0, VEC_ZERO, 1.0, 1.0)
			end
			news_manager.send_tip(db.actor, gc("st_start_refilling_tank_on_belt"), 0, nil, 5000)
		end
	end)
end

function on_game_start()
	RegisterScriptCallback("ActorMenu_on_item_drag_drop",on_item_drag_dropped)
end
