--[[
	Item Info Tooltip controlled appearance.
	11/11/2022
	This work is licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported License
	Author: Flueno
--]]


local enabled = true

local mod_hold_to_hide = 1
local mod_hold_or_click_to_show = 4
local default_mod = mod_hold_to_hide

local mod 	= mod_hold_to_hide -- current mod, could be change at runtime
local hold_key = DIK_keys.DIK_LMENU
local trigger_key = DIK_keys.DIK_LMENU -- DIK_LMENU /  DIK_LCONTROL /  DIK_SPACE /  DIK_CAPITAL
local use_alternative_key_listener = not (hold_key == DIK_keys.DIK_LMENU or hold_key == DIK_keys.DIK_LCONTROL)
local toggle_mode = false
local no_clicks = false

local enabled_delay_control = false
local default_delay = 350
local delay = default_delay
local delay_short = 110
local delay_on_gui_show = 1100
local delay_was_patched = {} -- delay patching (cached) for unconventional gui instances

--- Implementation relies on the fact that only UIInventory may be overlapped by other GUIs.
-- when overlapped gui is still participates in update loop  - need to ignore for proper item selection tracking
local alter_tooltip_at = { -- keys for delays, flags for mod alterations
	["UIInventory"] 	= enabled,
	["UIWorkshop"] 		= true,
	["UIItemSheet"] 	= true, -- details ui (shows on top of inv UI)
	["UIRepair"] 		= true, -- (repair + af-melter shows on top of inv UI)
	["UIMutantLoot"] 	= true,
	["UICook"] 			= true,
	["UIRecipe"] 		= true,
	["UICompanionInv"] 	= true, -- ?

}

local click_tracker
local gui_state
local function getId(t)
	if t and not t._pid then t._pid = string.format("%p", t) end
	return t and t._pid
end

function is_click_to_show_mod() return mod_hold_or_click_to_show == mod and not no_clicks end

local base_pass = utils_ui.UIInfoItem.Pass
function utils_ui.UIInfoItem:Pass(obj, sec)
	if enabled_delay_control then set_delay_if_not_patched(self.owner) end
	if not enabled or not alter_tooltip_at[gui_state.last_gui_shown_name] 	then return base_pass(self, obj, sec) end
	if is_click_to_show_mod() and gui_state:isGuiOverlayed(self.owner) 		then return base_pass(self, obj, sec) end

	-- binding inside :update call in order to react on forbidden in on_key_press keys
	if use_alternative_key_listener and toggle_mode then click_tracker:on_key_clicked(trigger_key, "UI", flip_modes) end

	local tt_candidate_id = obj and obj:id() or sec

	--- updating selection even if nothing is hovered (in order to reset selection if tt delay weren't reached)
	if is_click_to_show_mod() then click_tracker:updateSelectionToNewHoveredItem(tt_candidate_id) end

	if not (obj or sec) then return base_pass(self, obj, sec) end --- stop if nothing is even hovered

	------------------------ something is definitely hovered over ---------------------
	--------- listen to clicks while we are hovering over anything (but not in main inv)
	if is_click_to_show_mod() and not gui_state:isInventoryActive() then
		click_tracker:listen_to_mouse_click(tt_candidate_id)
	end

	local is_base_passed = base_pass(self, obj, sec)
	if not is_base_passed then return false end

	--------------------- something is definitely hovered over & delay passed ---------------------
	local hold_key_pressed = (key_state(hold_key) == 1)
	if mod_hold_to_hide == mod then
		if hold_key_pressed or not first_show_delay_passed() then
			self:Reset()
			return false
		else
			return true
		end
	elseif mod_hold_or_click_to_show == mod then
		if hold_key_pressed or click_tracker:isClickedOver(tt_candidate_id) then
			return true
		else
			self:Reset()
			return false
		end
	end
end

local function refreshClickListenerEnabledState(flag)
	click_tracker:enableInventoryItemKbEventListener((flag == nil or flag) and is_click_to_show_mod())
end

---- tootlip modes toggling -----
---------------------------------

function flip_modes()
	if enabled and toggle_mode and gui_state:is_any_displayed(alter_tooltip_at) then
		delay_was_patched = {}
		if mod_hold_to_hide == mod then
			mod = mod_hold_or_click_to_show
			for name, _f in pairs(alter_tooltip_at) do set_delay_at(name, delay_short) end
		elseif mod_hold_or_click_to_show == mod then
			mod = mod_hold_to_hide
			for name, _f in pairs(alter_tooltip_at) do set_delay_at(name, delay) end
		end
		refreshClickListenerEnabledState()
	end
end

function on_key_press(key)-- flip_modes; only Alt Ctrl Shift
	if enabled and toggle_mode and not use_alternative_key_listener and (trigger_key == key) and ui_mcm then
		ui_mcm.simple_press("tt_control", trigger_key, function() flip_modes() end)
	end
end

---- small initial tt delay -------
-----------------------------------

function first_show_delay_passed()
	local now = time_global()
	return delay_on_gui_show == 0
			or not gui_state:isInventoryActive()
			or (now > gui_state.last_gui_shown_ts + delay_on_gui_show)
end


---- tt delay alteration and state cleanups -----
-------------------------------------------------

local function get_contextual_delay()
	local contextual_delay = (mod_hold_or_click_to_show == mod) and delay_short or delay
	return alter_tooltip_at[gui_state.last_gui_shown_name] and contextual_delay or delay
end

function on_GUI_show(name, path)
	if not (enabled_delay_control or enabled) then return end
	--printf("show %s %s %s", name, path or 'nopath?', getId(gui_state:get_gui_ref(name)))
	gui_state:trackShown(name, path)

	if gui_state.is_overlayed then
		--printf("/// overlaying")
	elseif alter_tooltip_at[name] then
		mod = default_mod -- reset tt--mod on ui open
	end
	force_set_all_delays(get_contextual_delay())
	click_tracker:reset_item_selection()
	refreshClickListenerEnabledState(name == "UIInventory")
end

function on_GUI_hide(name, path)
	if not (enabled_delay_control or enabled) then return end
	--printf("hide %s %s %s", name, path or 'nopath?', getId(gui_state:get_gui_ref(name)))
	gui_state:trackHidden(name, path, function() force_set_all_delays(get_contextual_delay()) end)

	click_tracker:reset_item_selection()
	refreshClickListenerEnabledState(gui_state:is_displayed("UIInventory"))
end

local tooltip_owner_names = {"item_info", "upgr_info", "hint_wnd"}
function set_delay_at(name, delay)
	if not enabled_delay_control then return end
	set_delay_at_ref(gui_state:get_gui_ref(name), delay)
end

function set_delay_at_ref(gui_ref, delay)
	if enabled_delay_control and gui_ref then
		for _i,t_name in pairs(tooltip_owner_names) do
			if gui_ref[t_name] then gui_ref[t_name].delay = delay end
		end
	end
end

function force_set_all_delays(delay)
	if not enabled_delay_control then return end
	delay_was_patched = {}
	for name, _f in pairs(alter_tooltip_at) do set_delay_at(name, delay) end
end

function set_delay_if_not_patched(gui_ref)
	local gui_id = getId(gui_ref)
	if not delay_was_patched[gui_id] then
		set_delay_at_ref(gui_ref, get_contextual_delay())
		delay_was_patched[gui_id] = true
	end
end


-------------------------------------------------

function on_option_change()
	if ui_mcm then
		enabled = ui_mcm.get("tooltip_control/enabled")
		mod = ui_mcm.get("tooltip_control/tcontrol_mode") or mod_hold_to_hide
		hold_key = ui_mcm.get("tooltip_control/hold_key") or DIK_keys.DIK_LMENU
		trigger_key = ui_mcm.get("tooltip_control/trigger_key") or DIK_keys.DIK_LMENU
		toggle_mode = ui_mcm.get("tooltip_control/toggle_mode") or false
		use_alternative_key_listener = not (trigger_key == DIK_keys.DIK_LMENU or trigger_key == DIK_keys.DIK_LCONTROL)
		default_mod = mod
		no_clicks = ui_mcm.get("tooltip_control/no_clicks")
		local wasEnabledBeforeChange = enabled_delay_control
		enabled_delay_control = ui_mcm.get("tooltip_control/enabled_delay") or false
		if wasEnabledBeforeChange and not enabled_delay_control then
			-- revert to state as if mod were never enabled
			delay = default_delay
			force_set_all_delays(delay)
		end
		delay_on_gui_show = ui_mcm.get("tooltip_control/tooltip_gui_show_delay") or delay_on_gui_show
		delay = ui_mcm.get("tooltip_control/tooltip_delay") or default_delay
		delay_short = ui_mcm.get("tooltip_control/tooltip_click_delay") or 110

		alter_tooltip_at["UIItemSheet"] = ui_mcm.get("tooltip_control/tt_details")
		--alter_tooltip_at["UIWorkshop"] 	= ui_mcm.get("tooltip_control/tt_workshop")
		--alter_tooltip_at["UIRepair"] 	= ui_mcm.get("tooltip_control/tt_repair")
		--alter_tooltip_at["UIMutantLoot"]= ui_mcm.get("tooltip_control/tt_mutant_loot")
		--alter_tooltip_at["UICook"] 		= ui_mcm.get("tooltip_control/tt_cook")
		--alter_tooltip_at["UIRecipe"] 	= ui_mcm.get("tooltip_control/tt_recipe")

		refreshClickListenerEnabledState()
	end
end


function on_game_start()
	RegisterScriptCallback("on_option_change", on_option_change)
	RegisterScriptCallback("GUI_on_show", on_GUI_show)
	RegisterScriptCallback("GUI_on_hide", on_GUI_hide)
	RegisterScriptCallback("on_key_press",on_key_press)

	local utils = tooltip_control_utils
	click_tracker = utils.ClickTracker(enabled and is_click_to_show_mod())
	utils_ui.UICellContainer.OnKeyboard = click_tracker:hook_InventoryItemKbEvent(utils_ui.UICellContainer.OnKeyboard)
	utils_ui.UIInfoItem.Show 			= click_tracker:hook_OnTooltipShow(utils_ui.UIInfoItem.Show)
	gui_state = utils.GuiState()
	on_option_change()

end

--[[
local base_upgr_pass = utils_ui.UIInfoUpgr.Pass
function utils_ui.UIInfoUpgr:Pass(sec)
	if not enabled then return base_upgr_pass(self, sec) end

	if not sec then return base_upgr_pass(self, sec) end

	if is_click_to_show_mod() then click_tracker:updateSelectionToNewHoveredItem(sec) end
	if is_click_to_show_mod() and not gui_state:isInventoryActive() then
		click_tracker:listen_to_mouse_click(sec)
	end

	local is_base_passed = base_upgr_pass(self, sec)
	if not is_base_passed then return false end
	--------------------- something is definitely hovered over & delay passed ---------------------
	local hold_key_pressed = (key_state(hold_key) == 1)
	if mod_hold_to_hide == mod then
		if hold_key_pressed then
			self:Reset()
			return false
		else
			return true
		end
	elseif mod_hold_or_click_to_show == mod then
		if hold_key_pressed or click_tracker:isClickedOver(sec) then
			return true
		else
			self:Reset()
			return false
		end
	end
end
--]]