-- Extension script for weapon_cover_tilt_positions.script file
-- Open weapon_cover_tilt_positions.script file for instructions

if weapon_cover_tilt_positions then

	if not weapon_cover_tilt_positions.weapon_offsets then
		weapon_cover_tilt_positions.weapon_offsets = {}
	end
	
	local o = weapon_cover_tilt_positions.weapon_offsets
    
	o["wpn_eft_pb"] = {
		y = 0.32,
	}
	o["wpn_eft_pm"] = {
		y = 0.32,
	}
	o["wpn_eft_pm_tac"] = {
		y = 0.32,
	}
end