function actor_on_update()
	local run_coeff = grok_gotta_go_fast_mcm.get_config("gotta_go_fast_run")
	local sprint_coeff = grok_gotta_go_fast_mcm.get_config("gotta_go_fast_sprint")
	speed.add_speed("gotta_go_fast_run", run_coeff , false, true)
	speed.add_speed("gotta_go_fast_sprint", sprint_coeff, true, true)
end

local function actor_on_first_update()
	actor_on_update()
end

function on_game_start()
	RegisterScriptCallback("actor_on_first_update",actor_on_first_update)
	RegisterScriptCallback("actor_on_update",actor_on_update)
end
