item_weapon_attach_scope = item_weapon.attach_scope
item_weapon.attach_scope = function(item, weapon)
    local upgrade_state = utils_item.has_this_upgrade(weapon, nil, "up_fiftha_uzi")
    if (weapon:section() ~= "wpn_uzi" and weapon:section() ~= "wpn_uzi_mini") or upgrade_state then
        item_weapon_attach_scope(item, weapon)
    end
end

bones_per_upgrade = { 
    [true] = { "rail" },
    [false] = {}
}

class "hidebone_uzi_upgrade" (object_binder)

function hidebone_uzi_upgrade:__init(obj) super(obj)
end

function bind(obj)
    obj:bind_object(hidebone_uzi_upgrade(obj))
end

function hidebone_uzi_upgrade:update(delta)
    object_binder.update(self, delta)
    
    local upgrade_state = utils_item.has_this_upgrade(self.object, nil, "up_fiftha_uzi")
    if upgrade_state ~= self.upgrade_state then
        self.upgrade_state = upgrade_state
        
        for _,bone_name in pairs(bones_per_upgrade[upgrade_state]) do
            self.object:set_bone_visible(bone_name, true, true, true)
            self.object:set_bone_visible(bone_name, true, true, false)
        end
        
        for _,bone_name in pairs(bones_per_upgrade[not upgrade_state]) do
            self.object:set_bone_visible(bone_name, false, true, true)
            self.object:set_bone_visible(bone_name, false, true, false)
        end
    end
end