-- If you don't use MCM, change your defaults from here.
local defaults = {
	["campfire_regen"] = 1,
	["increase_mult"] = 1,
	["walk_mult"] = 1,
	["run_mult"] = 1,
	["sprint_mult"] = 1,
	["jump_mult"] = 1,
	["sleep_regen_per_hour"] = 8,
	["max_fatigue"] = 75,
	["debug_mode"] = false,
}

function get_config(key)
	if ui_mcm then return ui_mcm.get("fatigue/"..key) else return defaults[key] end
end

function on_mcm_load()
	op = { id= "fatigue",sh=true ,gr={
			{ id= "title",type= "slide",link= "ui_options_slider_player",text="ui_mcm_fatigue_title",size= {512,50},spacing= 20 },
			{id = "campfire_regen", type = "track", val = 2, min=1,max=100,step=1, def = 1},
			{id = "increase_mult", type = "track", val = 2, min=0.1,max=3,step=0.1, def = 1},
			{id = "walk_mult", type = "track", val = 2, min=0.1,max=3,step=0.1, def = 1},
			{id = "run_mult", type = "track", val = 2, min=0.1,max=3,step=0.1, def = 1},
			{id = "sprint_mult", type = "track", val = 2, min=0.1,max=3,step=0.1, def = 1},
			{id = "jump_mult", type = "track", val = 2, min=0.1,max=3,step=0.1, def = 1},
			{id = "sleep_regen_per_hour", type = "track", val = 2, min=4,max=30,step=1, def = 8},
			{id = "max_fatigue", type = "track", val = 2, min=10,max=95,step=5, def = 75},
			{id = "debug_mode", type = "check", val = 1, def = false},
		}
	}

	return op
end