-- If you don't use MCM, change your defaults from here.
local gc = game.translate_string
local defaults = {
	["winter"] = true,
	["wind"] = 1,
	["rain"] = 1,
	["time"] = 1,
	["sun"] = 1,
	["campfire"] = 1,
	["move"] = 1,
	["outfit"] = 1,
	["artefact"] = 1,

	["hud"] = false,
	["keybind"] = 50,
	["main_hud_position_x"] = 884,
	["main_hud_position_y"] = 189,
	["main_bar_text_mode"] = false,
	["main_hud_font"] = 4,
	["main_hud_descr_type"] = 2,
	["thermo_hud_position_x"] = 980,
	["thermo_hud_position_y"] = 50,
	["thermo_bar_text_mode"] = false,
	["thermo_hud_font"] = 4,
	["thermo_hud_descr_type"] = 1,

	["sickness"] = 1,
	["medicine"] = 1,
	["sleep"] = 1,
	["food_cooling"] = 1,
	["consumables"] = 1,
	["ppe"] = true,
	["debugx"] = false,
}

local keybind_table = {
	{7, "6"},
	{8, "7"},
	{9,"8"},
	{10,"9"},
	{11,"0"},
	{22,"U"},
	{23,"I"},
	{24,"O"},
	{25,"P"},
	{35,"H"},
	{36,"J"},
	{37,"K"},
	{38,"L"},
	{44,"Z"},
	{45,"X"},
	{46,"C"},
	{47,"V"},
	{48,"B"},
	{49,"N"},
	{50,"M"},
}

local hud_font_table = {
	{1, "Small"},
	{2, "Medium"},
	{3, "DI"},
	{4, "Letterica 16"},
	{5, "Letterica 18"},
	{6, "Letterica 25"},
	{7, "Graffiti 19"},
	{8, "Graffiti 22"},
	{9, "Graffiti 32"},
	{10, "Graffiti 50"},
}

function get_config(key)
	local value = ui_mcm and ui_mcm.get("cold_system/"..key) or nil
	if value == nil then value = defaults[key] end

	if type(defaults[key]) == "boolean" then
		if value == true or value == 1 or value == "1" or value == "true" then return true end
		return false
	end

	return value
end

function on_mcm_load()
	op = { id= "cold_system",sh=true ,gr={
			{ id= "title",type= "slide",link= "ui_options_slider_player",text="ui_mcm_cold_system_title",size= {512,50},spacing= 20 },

			{ id= "title"				   ,type= "title"	 ,text= "ui_mcm_cold_system_header_main" 			,align= "l"	,clr= {255,200,200,200}	},
			{id = "winter", type = "check", val = 1, def = true},
			{id= "divider", type = "line" },
			{id = "wind", type = "track", val = 2, min=0,max=5,step=0.05, def = 1},
			{id = "rain", type = "track", val = 2, min=0,max=5,step=0.05, def = 1},
			{id = "time", type = "track", val = 2, min=0,max=5,step=0.05, def = 1},
			{id = "sun", type = "track", val = 2, min=0,max=5,step=0.05, def = 1},
			{id = "campfire", type = "track", val = 2, min=0,max=5,step=0.05, def = 1},
			{id = "move", type = "track", val = 2, min=0,max=5,step=0.05, def = 1},
			{id = "outfit", type = "track", val = 2, min=0,max=5,step=0.05, def = 1},
			{id = "artefact", type = "track", val = 2, min=0,max=5,step=0.05, def = 1},

			{id= "divider", type = "line" },
			{ id= "title"				   ,type= "title"	 ,text= "ui_mcm_cold_system_header_hud" 			,align= "l"	,clr= {255,200,200,200}	},
			{id = "hud", type = "check", val = 1, def = false},
			{ id= "keybind"	,type= "list", val = 2, def = 50, content = keybind_table, no_str = true},
			
			{id= "divider", type = "line" },
			{id = "main_hud_position_x", type = "track", val = 2, min=0,max=1000,step=1, def = 884},
			{id = "main_hud_position_y", type = "track", val = 2, min=0,max=1000,step=1, def = 189},
			{id = "main_bar_text_mode", type = "check", val = 1, def = false},
			{ id= "main_hud_font"	,type= "list", val = 2, def = 4, content = hud_font_table, no_str = true},
			{ id= "main_hud_descr_type"	,type= "list", val = 2, def = 2, content = { {1, gc("cold_main_hud_value")}, {2, gc("cold_main_hud_percent")} }, no_str = true},

			{id= "divider", type = "line" },
			{id = "thermo_hud_position_x", type = "track", val = 2, min=0,max=1000,step=1, def = 980},
			{id = "thermo_hud_position_y", type = "track", val = 2, min=0,max=1000,step=1, def = 50},
			{id = "thermo_bar_text_mode", type = "check", val = 1, def = false},
			{ id= "thermo_hud_font"	,type= "list", val = 2, def = 4, content = hud_font_table, no_str = true},
			{ id= "thermo_hud_descr_type"	,type= "list", val = 2, def = 1, content = { {1, gc("cold_thermo_hud_short")}, {2, gc("cold_thermo_hud_long")} }, no_str = true},

			{id= "divider", type = "line" },
			{ id= "title"				   ,type= "title"	 ,text= "ui_mcm_cold_system_header_misc" 			,align= "l"	,clr= {255,200,200,200}	},

			{id = "sickness", type = "track", val = 2, min=0.05,max=5,step=0.05, def = 1},
			{id = "medicine", type = "track", val = 2, min=0,max=5,step=0.05, def = 1},
			{id = "sleep", type = "track", val = 2, min=0,max=5,step=0.05, def = 1},
			{id = "food_cooling", type = "track", val = 2, min=0.05,max=5,step=0.05, def = 1},
			{id = "consumables", type = "track", val = 2, min=0,max=5,step=0.05, def = 1},
			{id = "ppe", type = "check", val = 1, def = true},
			{id = "debugx", type = "check", val = 1, def = false},
		}
	}

	return op
end
