function on_mcm_load()
  op = {
    id = "bullet_shell_sounds", 
    sh = true, 
    gr = {
      {id = "title", type = "slide", link = "ui_options_slider_player", text = "ui_mcm_title_bullet_shell_sounds", size = {512, 50}, spacing = 20},
      {id = "enabled", type = "check", val = 1, def = true},
      {id = "volume", type = "track", val = 2, min = 0, max = 1, step = 0.01, def = 1}
    }
  }
  return op
end
