-- If you don't use MCM, change your defaults from here.
local defaults = {
	["hud_snd"] = true,
}

function get_config(key)
	if ui_mcm then return ui_mcm.get("xcvb_achievements/"..key) else return defaults[key] end
end

function on_mcm_load()
	op = { id= "xcvb_achievements",sh=true ,gr={
			{ id= "title",type= "slide",link= "ui_options_slider_player",text="ui_mcm_xcvb_achievements_title",size= {512,50},spacing= 20 },

			{id = "hud_snd", type = "check", val = 1, def = true},
		}
	}

	return op
end
